### ISSUE TITLE
The new 5.0 VRMocap_PlayerPawn_BP.uasset file is not displayed 4.7 Normal

### ISSUE THREAD

**Issue by lifenots** [Megasteakman/VRMocap#10]
The new 5.0 VRMocap_PlayerPawn_BP.uasset file is not displayed. 4.7 is normal, but the 4.7 upgrade to 5.0VRMocap_PlayerPawn_BP.uasset does not display this content.

**Comment by Megasteakman** [comment]
Unfortunately, UE 5 is early access, and 4.27 projects do not import properly.  I hear that this will be fixed by the full release, but for now just use older git releases that are 4.26 (the changelist should have '4.27' in any of the commits I did after upgrading the project).
