### ISSUE TITLE
Possible without headset at all?

### ISSUE THREAD

**Issue by reactor81** [Megasteakman/VRMocap#14]
Hi, I just purchased 4 base stations and 7 trackers to give VRMocap a go! My only concern atm is that I did not purchase a headset. 

I do have a Quest 1 headset, but I didn't see you using a headset in your videos. 

Is it possible to do room configuration and everything I need without any headset at all?

Thank you!

**Comment by reactor81** [comment]
Ah, I just saw your post here https://github.com/Megasteakman/VRMocap/issues/4 

It links to LiveLinkXR as a way to avoid a headset? Interesting, I thought LiveLinkXR was just a required plugin regardless of headset/no headset.

**Comment by reactor81** [comment]
Hmm perhaps I will be able to use my quest.

**Comment by Megasteakman** [comment]
Near the bottom of this page, there are instructions on how to use trackers without a headset.  https://docs.unrealengine.com/4.26/en-US/AnimatingObjects/SkeletalMeshAnimation/LiveLinkPlugin/Livelinkxr/

I've never done this before, and wouldn't really recommend it, but I think it is possible.

I typically use the system viewing the computer screen, so it's possible to use it without a headset.  I don't believe the quest will work because there aren't enough tracked points, and I'm not sure if the quest steamvr world coordinates will match the trackers.  Let me know if it works though!

**Comment by ChenPENGPENGcpp** [comment]
> Near the bottom of this page, there are instructions on how to use trackers without a headset. https://docs.unrealengine.com/4.26/en-US/AnimatingObjects/SkeletalMeshAnimation/LiveLinkPlugin/Livelinkxr/
> 
> I've never done this before, and wouldn't really recommend it, but I think it is possible.
> 
> I typically use the system viewing the computer screen, so it's possible to use it without a headset. I don't believe the quest will work because there aren't enough tracked points, and I'm not sure if the quest steamvr world coordinates will match the trackers. Let me know if it works though!

No headset is doable. I did it. 
You can set up your steam VR with reference to the video below
https://youtu.be/LiV8RhzvUHI

If you’re going to use the index controller for finger capture, you need to buy two extra USB dongles.
like this: https://vrdongles.com/products/watchman-dongle-for-steamvr-and-htc-vive
This item is not the only option; any other USB dongle that can wirelessly connect to the index controller is fine.
Normally, the index controller is connected wirelessly to the headset, so without the headset, you need two extra USB dongles.

Another thing to note is that when you set up a base station, there’s no way to connect the base station to the computer via Bluetooth, (the Bluetooth module that connects the HTC Vive headset to the computer)   so you have to poke a hole in the back of the base station, to reset the channel of the base station, the following link is for discussion：
https://www.reddit.com/r/vive_vr/comments/c8bil1/is_there_a_way_to_change_base_station_20_channels/

If you only use VR Mocap for motion capture in UE, you don’t need to use quest headset. 

If you want to mix quest with the Index Controller and Vive Tracker for other games, then you need to merge quest with steam VR for calibration, a search for “Steam VR without a headset” will give you some ideas, but I haven’t tried this combination.

English is not my native language. Please forgive me if there is any ambiguity.
