### ISSUE TITLE
Attach Actor to Component is floaty

### ISSUE THREAD

**Issue by Megasteakman** [Megasteakman/VRMocap#2]
The attach actor to component logic used in the CC3Metahuman Hybrid is floaty.

**Comment by chnl** [comment]
Trying to straight metahuman actor no cc3or hybrid.  Getting compile errors on play. Could it be skeletal remapping?
Message Log:
Blueprint Runtime Error: "Accessed None trying to read property MocapActor_SkeletalMesh". Blueprint:  MocapActorSFXGenerator_Component Function:  Execute Ubergraph Mocap Actor SFXGenerator Component Graph:  EventGraph Node:  Calculate Velocity From Position History
 Blueprint Runtime Error: "Accessed None trying to read property ActorPointOfReference". Blueprint:  MocapActorSFXGenerator_Component Function:  Execute Ubergraph Mocap Actor SFXGenerator Component Graph:  EventGraph Node:  Calculate Velocity From Position History
Outputlog:
LogLinker: Warning: [AssetLog] E:\VirtualProduction\Projects\VRmoCap\Content\VRMocap\Components\EmotionAnimations\CC3_emotion_angry_anim.uasset: Failed to load '/Game/iCloneDefaultMale/iCloneCC3DefaultMale_Skeleton': Can't find file.
