### ISSUE TITLE
Can't Actor Metahuman。

### ISSUE THREAD

**Issue by yodfz** [Megasteakman/VRMocap#20]
I have import Metahuman in projects。

and set Metahuman body :

- `Adnimation Mode` -> 'Use Animation Blueprint'
- 'Anim Class' -> 'VRMocapActor_Metahuman_AnimBP'
- Add MocapActor Component

But,Can't calibration this。

![image](https://user-images.githubusercontent.com/1439163/149861983-35ff4c16-d572-478c-83e9-d05069679db7.png)

**Comment by yodfz** [comment]
I use Vive Tracker 3.0 and Vive Controller

**Comment by yodfz** [comment]
and error message:
`Accessed None trying to read property K2Node_DynamicCast_AsVRMocap_Actor_Metahuman_Anim_BP`

**Comment by yodfz** [comment]
and HUD error
`CastToMetahumanFailed`

**Comment by Megasteakman** [comment]
I don't believe those errors are the issue.  Did you set up the inputs for your VR controllers?  Also, you have to make sure to click into the viewport to actually enable input in game.  Also, make sure you are running in game mode and not simulate.  If you can't get inputs working, I set up a node after begin play that will auto calibrate after 15 seconds or so.

Other than that, I don't think I have enough information to figure this out.  Maybe turn on the 'Debug Strings Hud' on the VRMocap_PlayerPawn_BP and look out for any red text.  You can often search that text in the blueprint to see what part of the process is having trouble.

**Comment by yodfz** [comment]
> I don't believe those errors are the issue. Did you set up the inputs for your VR controllers? Also, you have to make sure to click into the viewport to actually enable input in game. Also, make sure you are running in game mode and not simulate. If you can't get inputs working, I set up a node after begin play that will auto calibrate after 15 seconds or so.
> 
> Other than that, I don't think I have enough information to figure this out. Maybe turn on the 'Debug Strings Hud' on the VRMocap_PlayerPawn_BP and look out for any red text. You can often search that text in the blueprint to see what part of the process is having trouble.

Ok,I saw issues [11](https://github.com/Megasteakman/VRMocap/issues/11) question like me question.I'll have a try.
waiting for me new message.

**Comment by yodfz** [comment]
> 我不相信这些错误是问题所在。您是否为 VR 控制器设置了输入？此外，您必须确保单击视口以实际启用游戏中的输入。另外，请确保您在游戏模式下运行而不是模拟。如果您无法使输入正常工作，我会在开始播放后设置一个节点，该节点将在 15 秒左右后自动校准。
> 
> 除此之外，我认为我没有足够的信息来解决这个问题。也许打开 VRMocap_PlayerPawn_BP 上的“Debug Strings Hud”并注意是否有任何红色文本。您通常可以在蓝图中搜索该文本，以查看流程的哪个部分出现问题。

emm.i can play actor.but,acimation is error.
look this.
https://youtu.be/1k3YeW_VwXE
