### ISSUE TITLE
Metahuman Animation Error

### ISSUE THREAD

**Issue by yodfz** [Megasteakman/VRMocap#21]
look this video。
https://youtu.be/1k3YeW_VwXE
bind tracker is done。
but,right hand position is error。

**Comment by Megasteakman** [comment]
I think something changed in the Metahumans when they hit 0.5.  I've made a new control rig that should fix your issue.

https://github.com/Megasteakman/VRMocap/commit/24e077a601efecbbbb52a6be14178eddfce8fcee

Let me know if it works for you.

**Comment by yodfz** [comment]
ok,i‘ll try

**Comment by yodfz** [comment]
very good,problem solved。and chest tracker  is required。
if not chest tracker,chest to hip height in folding。
