### ISSUE TITLE
Metahuman dislocated neck and wrists rotation.

### ISSUE THREAD

**Issue by kuroderuta** [Megasteakman/VRMocap#22]
I’m using the HMD capture with index headset and controllers as well as 4 vive trackers (chest, pelvis, feet). After calibrating the neck on my metahuman gets longer and leans forward. I have tried a couple of things like making myself smaller or larger and changing the position of the chest tracker to make the neck look natural but none of that worked. Similarly I cannot get the wrists rotation right, they are always pointing downwards relative to the arm no matter the position during calibration.

**Comment by Megasteakman** [comment]
Your test since this was submitted look pretty good.  Can I close this issue?
