### ISSUE TITLE
Metahuman pelvis swim.

### ISSUE THREAD

**Issue by kuroderuta** [Megasteakman/VRMocap#23]
My setup includes Index HMD capture and controllers as well as 4 vive trackers (chest, pelvis, feet). Trying to capture an actor walking results in the hips rotating from left to right together with the spine bones above. Mocap actor and Metahuman are roughly the same height during the calibration.

Video of the issue:
https://youtu.be/R4MXSTEzex0

**Comment by Megasteakman** [comment]
I've redone the metahuman control rig in the latest update: let me know if this fixes your issues: https://github.com/Megasteakman/VRMocap/commit/5d8851856eeeffbd9ed16f33d8edf25bc4205100

**Comment by Megasteakman** [comment]
Unfortunately I don't think I can solve this one, but you are welcome to take a look at the metahuman control rig and submit a fix if you can find it!  Thanks!

**Comment by kuroderuta** [comment]
Can you guide me into which changes of the newest update could've caused this? I understand it is something in the new metahuman rig?

**Comment by Megasteakman** [comment]
Every change would be in the metahuman control rig.  I changed properties in the neck to make that more stable, but I guess it had knock on effects.  You can download the prior commit and just drag in the control rig file using file explorer (you might have to place it in a different directory than the one in the vr mocap project so you don't override the prior one.  Then open both side by side and see if you can make a combination that works for you.

All the IK stuff happens near the bottom of the graph.  There are prior versions of the system also disconnected and placed on the sides that might be helpful.

**Comment by kuroderuta** [comment]
I identified that it was the head IK nodes that changed this behavior. Additionally the discrepancy between standing and sitting position of the head is influenced by the distance of the Pelvis and Chest trackers. While standing we are naturally a bit more straight than when sitting. I haven't figured out where and how to change this yet however.

**Comment by Megasteakman** [comment]
I just released a new version where I adjusted the blend between the fake head position and the real head position.  It should be more like it was, but let me know what you think.

**Comment by kuroderuta** [comment]
Sorry for the delay, life got in the way. I tried the updates and yes that is better however the issue with the elongated neck came back from earlier. But out of the two issues i'd rather deal with that one..
