### ISSUE TITLE
Do we need base sations/lighthouses?

### ISSUE THREAD

**Issue by Kilybaii** [Megasteakman/VRMocap#4]
Hey,

Thanks for this!

Found it very useful for our our new vr project.

Qq do we need base stations? Its not listed under hardware. And if we do, which one do you recommend? And how many?

Many thanks

**Comment by Megasteakman** [comment]
Sorry, I've been in VR so long that I forget that not everyone knows about vive trackers.  Vive trackers use HTC/Valve base stations to track.  I don't believe it is easy to use these without a VR Headset, but you might be able to hack things using this: https://docs.unrealengine.com/4.26/en-US/AnimatingObjects/SkeletalMeshAnimation/LiveLinkPlugin/Livelinkxr/

**Comment by Kilybaii** [comment]
Thanks for the info! And sorry for my late reply I thought already replied. I intended to respond last week but never clicked send...
I now have my base stations and my trackers and will try to follow your instructions.
