### ISSUE TITLE
Error when trying to import VR mocap player pawn

### ISSUE THREAD

**Issue by Kilybaii** [Megasteakman/VRMocap#5]
Hi There,

We are following your video step by step.

We Added all the plugins and tried to add the VR mocap player pawn (camera).

First off all it is not displaying like on your video (in unreal engine 4 last version and unreal 5). 
then we got an error (the following member variables in blueprint have invalid type. would you like to remove them.)
When we click ok, we then are able to add the actor but its saying blueprint and doesnt show a camera like on your video.

I'm using windows 10.

Can you please help.

Many thanks

![Screenshot (2)](https://user-images.githubusercontent.com/87229753/127181681-82877bb1-ee83-4761-a52b-ce1e504805f6.png)

**Comment by Megasteakman** [comment]
What version of Unreal are you using?  I've never encountered this error before on 4.26 or 5.

The variables this message is mentioning are structs that are located in VRMocap\Components\Structs.  Maybe download the files from github again and replace everything in this folder?

**Comment by Kilybaii** [comment]
We tried with 4.26.2 and early access 5.

Same result on both. we also reinstalled unreal and redownloaded the mocap zip file and replaced it but we go the same error.

Thanks

![image](https://user-images.githubusercontent.com/87229753/127225544-d61e9aa7-a7a9-45c1-a882-459e33ac335e.png)

**Comment by Kilybaii** [comment]
this is what it looks like when we drag and drop the spectator camera or the pawnt in the scene

![image](https://user-images.githubusercontent.com/87229753/127234042-9cf5bcd1-4933-4395-8bdd-74f3def6d1ad.png)

**Comment by Megasteakman** [comment]
I think I was able to reproduce your issue.  If you drag in the whole github directory, assets aren't where the system expects they should be.  The project should be "Content/VR Mocap."  I think you dragged in the whole github directory, which has some extra files in there you don't need like the license/key bindings, github metadata.  Let me know if this works for you.

**Comment by Kilybaii** [comment]
Many thanks it resolved the issue.

**Comment by Kilybaii** [comment]
Actually it completely resolved the issue in unreal 4.26.2 but not in 5.

The vr mocap spectator camera and scnene locator are now showing but not the player pawn. As seen on the screenshot below.

![image](https://user-images.githubusercontent.com/87229753/127448909-ecccb23c-f0db-446b-b48b-310d3afdab6b.png)

**Comment by Kilybaii** [comment]
I think it's a missing plugin. Unreal 4 notified us  the first time we tried to drag and drop the player pawn in the scene. Unrl 4  asked if we wanted to enable it and once we restarted unreal it was working. however unreal 5 doesn't notify us.

**Comment by Kilybaii** [comment]
its working in 5 aswell now
