### ISSUE TITLE
Assistance for set up

### ISSUE THREAD

**Issue by Kilybaii** [Megasteakman/VRMocap#7]
Hi there,

Thanks a lot for your videos and explanations.

We have a Vtuber project and we have been struggling with the set up. (Vive trackers, index controllers, iphone, unreal engine). We have our own 3d model (fbx file)

We would like to know if you could assist us or help us find someone who could (we can discuss an arrangement)

Please let us know asap, we are desesparate :)

Many thanks!

M.

**Comment by Megasteakman** [comment]
I can possibly assist if the skeleton is a mannequin, metahuman or character creator 3 model, but unfortunately the way the system works is it needs a control rig and animation blueprint created for each custom skeleton (as well as something to define the skeleton bones and add it to the player pawn in the mocap actor component).  Unfortunately I don't have enough time for the next month to work out a custom skeleton, although there are the 'hooks' in the program for an 'Unknown' skeleton type that with a little more work might be able to work.  Right now the program hard crashes when using this control rig set up.

Other than that, you might want to look into Animation Prep Studio's Luxor, which is much more accepting of various skeletons.  You should be able to stream that data into Unreal Engine from there.

**Comment by Kilybaii** [comment]
Hi, thank you so much for your reply.

We understand that you have a limited amount of spare time. What we really need is to get this thing working  asap on any system. We found the vive mocap kit and other solutions, we'll also look into animation prep but  we'll need someone to spend a few hours with us so we could do the set up together (remote session). We'd also need someone who could show us how to record videos and do live streaming within unreal engine. As you can tell we are not really technical :)

If you or anyone you know would have time to spend a few hours with us we'd be happy to discuss a budget for it. 

Many thanks

M.

M.

**Comment by sv3nk** [comment]
@Kilybaii 

It sounds like you are fairly new to Unreal Engine. There are many beginner tutorials to get a basic understanding of how Unreal Engine works. Should not take more than 1 or 2 days and is a great start.

Megasteakman also created two videos for the setup of VRMocap on Youtube.

Quick Start
[https://www.youtube.com/watch?v=w9ZhOewWkAQ](https://www.youtube.com/watch?v=w9ZhOewWkAQ)

Complete Setup Guide
[https://www.youtube.com/watch?v=w9ZhOewWkAQ](https://www.youtube.com/watch?v=crv6AIbadSo)

With the second video, a first setup should be achievable.

If your character is not based on CC3 or the Unreal Mannequin, I suggest to create a simple Metahuman and use it for a first setup. It will help you understand how the VRMocap Solution works. This will also help you decide whether VRMocap is the solution you are looking for. 

If, after getting your test setup running, you like VRMocap, you can either try to make it work with your custom 3D model, or you look around for a different solution.
You could also look to recreate your existing 3D model.

My guess is that you are inspired by CodeMiko or similar VTtubers and want to try something similar.
Please keep in mind that:
1. This project is WIP
2. CodeMiko uses a professional Mocap Suit and Software that allow for cleaner animations and behaviour

**As for the budget topic: I would hardly advise against throwing money at someone to do a one-time setup for you.** 
A complete setup and great production quality require regular maintenance and tweaks. 
An update to the VRMocap solution might break your setup and require you to spend even more money.
Updates like different clothing will also require a decent understanding of the solutions you are using.

**Comment by Kilybaii** [comment]
Hey @sv3nk thank you so muh for your reply.

We did actually watch these videos already and really need to use our own Model 3d (fbx file). We unfortunately don't have enough time experiment and do the set up ourselves but need someone to show us how to do it (set up + record videos + live stream and maybe also how to change the backgrounds in unreal). We are aware this is a WIP and are ready to use any system that will allow us to use our vive trackers for mocap. We definitely looked at Codemiko who uses an Xsens mocap suit. Afrer a bit of investigation we found out the Rokoko and pn3 are also very good and that the vive trackers not far behind when used correctly (we don't need something as precise as Codemiko).

If we knew that setting up the Vive trackers for Mocap would had been as challening we would have bought a pn3 or a rokoko but its too late now and we've seen some impressing results with the vive trackers.

So we are still looking for someone who would be willing to spend a couple of hours helping us with the set up.

Please help lol

Many thanks

M.

**Comment by Kilybaii** [comment]
@Megasteakman @sv3nk   if you know anyone who would be willing to spend some time with us going through the set up (animation prep, vive mocap kit or any other system) please let us know it would be much appreciated (mae@baikily.com) many thanks

**Comment by sparkVFX** [comment]
> @Megasteakman @sv3nk if you know anyone who would be willing to spend some time with us going through the set up (animation prep, vive mocap kit or any other system) please let us know it would be much appreciated ([mae@baikily.com](mailto:mae@baikily.com)) many thanks

hi, currently I used this system to apply my  custom skeleton，and the result are acceptable I think。this is the video link：https://vimeo.com/613534313

@Megasteakman thanks
