### ISSUE TITLE
Issue with IK

### ISSUE THREAD

**Issue by zzilch** [Megasteakman/VRMocap#8]
Thanks for making this amazing project open source! I am seeking for a decent VR Mocap solution recently (mostly on Unity), and your project gives me hope in Unreal.
However, I find the IK middleware is crucial to get stable, accurate and natural poses. For example, the pose solved by Manus Polygon and IKinema Orion looks better than the pose solved by Final IK.
I heard that Unreal 5 has a more advanced IK system than Unreal 4. Have you compared the differences between them? Are the poses better in Unreal 5?

**Comment by Megasteakman** [comment]
I think you could set up something very similar with Unity using their new runtime rigging.  A tool like Manus and Polygon would probably be better, but I couldn't afford solutions like that so I made my own.  The only drawback I have found with Unreal is that you need to set up an animation blueprint per unique skeleton.  You can always retarget an animation blueprint to a new skeleton, but there's also additional steps to do in the VRMocap Player Pawn and the Mocap Actor component.

**Comment by zzilch** [comment]
Thanks for your advice!
